apiVersion: batch/v1
kind: CronJob
metadata:
  name: torus-demo-cronjob
  namespace: torus
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cleanup
              image: busybox
              args:
                - /bin/sh
                - -c
                - echo "Torus CronJob $(date) ran"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
