apiVersion: batch/v1
kind: Job
metadata:
  name: torus-demo-job
  namespace: torus
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hello
          image: busybox
          args:
            - /bin/sh
            - -c
            - date; echo "Torus demo job ran successfully"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
